### Sign in as an existing user
POST http://localhost:3000/auth/login
content-type: application/json

{
  "email": "jerome.fabricante1@opsolutions.biz",
  "password": "testpassword123@"
}

### Get the authenticated user
GET http://localhost:3000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Implcm9tZS5mYWJyaWNhbnRlMUBvcHNvbHV0aW9ucy5iaXoiLCJpZCI6Niwicm9sZSI6IlNBIiwiZGlzcGxheU5hbWUiOiJKZXJvbWUgRmFicmljYW50ZSIsImlhdCI6MTY1NjQ2ODg3MiwiZXhwIjoxNjU2NDY4OTMyfQ.8wUE9VpGRu8FIt-NLaYILHGEMcccLsTLWRM6P53XSME